apiVersion: apps/v1
kind: Deployment
metadata: 
  name: python-deployment
  labels:
    app: python-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: python-app
  template:
    metadata:
      labels:
        app: python-app
    spec:
      containers:
      - name: python-container
        image: rkreber/python-image:v0.1.1
        imagePullPolicy: "Always"
        env:
        - name: SERVER
          value: "http://events-internal"
        - name: PORT 
          value: "5000"
        resources:
          requests:
            memory: "128Mi"
            cpu: "0.1"
          limits:
            memory: "256Mi"
            cpu: "0.2"