apiVersion: v1
kind: Service
metadata: 
  name: python-lb
  labels:
    app: python-app
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 5000
  selector:
    app: python-app
  type: LoadBalancer