apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: react
  name: react-deployment
  labels:
    app: react-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: react-app
  template:
    metadata:
      labels:
        app: react-app
    spec:
      containers:
      - name: react-container
        image: rkreber/react-image:v0.1.1
        imagePullPolicy: "Always"
        env:
        - name: SERVER
          value: "http://events-internal"
        resources:
          requests:
            memory: "128Mi"
            cpu: "0.1"
          limits:
            memory: "256Mi"
            cpu: "0.2"
