apiVersion: v1
kind: Service
metadata:
  labels:
    app: events-internal
  name: events-internal
  namespace: react #need to put in react NS and copy IP into .env folder
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 8082
  selector:
    app: events-internal
  type: LoadBalancer